version: '2'
services:
  postgres:
    build: ./postgres/
    image: wur/postgres-irods
    hostname: postgres
  irods:
    build: ./irods/
    image: wur/irods
    ports: 
      - "1247:1247"
      - "20000-20199:20000-20199"
    hostname: irods
    volumes: 
      - /mnt/data:/var/lib/irods/Vault
  davrods:
    build: ./davrods/
    image: wur/davrods
    ports:
      - "80:80"
    hostname: davrods
