version: '2'
services:
  postgres:
    build: ./postgres/
    image: cyverseuk:postgres-irods
  irods:
    build: ./irods/
    image: cyverseuk:irods
    ports: 
      - "1247:1247"
      - "20000-20199:20000-20199"
    hostname: cyverse-iRods
    volumes: 
      - /mnt/irods/irods_agave:/var/lib/irods/Vault
